## data load settings
data_path = IUP_Regression_Model/data/SAGE-SCIA-OMPS.nc
# time_format = %Y%m
# time_var = time
# lat_var = lat
# lev_var = alt
# lev_var_unit = km
# o3_var = ozone
# o3_var_unit = abs_molec/cm³


o3_var = ozone
o3_var_unit = Number Density [molec/cm³]
o3_type =
# o3_var_anom = False
time_var = time
# Changes which variable will be used as the time variable, if none is chosen then the first one will be used
# time_dim = 1
#time_format = %Y%m

## Changes the variable name that will be used for the first dimension of the ozone variable; Here, the first dimension will use the lat variable instead and gives it the tag "lat"
# additional_var_3_index = lat
additional_var_3_tag = lat
additional_var_2_limit = 15, 45
additional_var_3_limit = 3, 14
additional_var_3_unit = Latitude
additional_var_2_unit = Altitude [m]
# additional_var_2_tag = alt
# add_variable_2_index = longitude


## trend settings
inflection_point = 1996-01, 2000-01
inflection_method = ind, gap, ind
start_date = 1979-01
end_date = 2024-12
# averaging_window = 1, 2, 3
# anomaly = True
# anomaly_method = rel
filter_internal_fraction = 0.5
filter_fill_fraction = 0.7

## First part of the ozone unit is either "abs_" or "anom_" and the second part can be "rel" (only for anomalies), "molec/cm³", "ppmv", "DU", "DU/km"
# default_seasonal_component = 2
# trend_seasonal_component = 2
# intercept_seasonal_component = 2
## 1 = annual; 2 = semi-annual; 3 = tri-annual; 4 = quarter-annual
trend_method = 2
intercept_method = 2
## Methods: 0 = disabled; 1 = singular; 2 = harmonically; 3 = 12 months

## proxy settings
default_proxy_method = 1

## general options
tag_name_lat = lat, latitude, latrange, lat_bands
tag_name_lon = lon, longitude, lonrange
tag_name_alt = alt, altitude, lev, level
tag_name_time = time, date


## default data paths
proxy_path = data/Proxies_Timeseries_202503.txt
aod_path = data/AOD_timeseries_1980-2022_10lat.txt
save_folder_path = save_folder
